"""Integration test: structured Task flows through to the iteration prompt.

Confirms that ``build_iteration_prompt`` renders the structured XML
block when a ``Task`` is passed and falls back to the legacy plain
``<task>desc</task>`` block when not. This is the contract the engine
relies on after the Task plumbing PR — both the principal and the
critic see whichever block is produced here.
"""

from __future__ import annotations

from infinidev.engine.loop.context import build_iteration_prompt
from infinidev.engine.loop.models import LoopState
from infinidev.engine.orchestration.task_schema import Task, task_from_free_text


def _empty_state() -> LoopState:
    return LoopState()


def test_legacy_path_uses_plain_task_block():
    state = _empty_state()
    out = build_iteration_prompt(
        "implement JWT auth",
        "expected: working endpoint",
        state,
    )
    assert "<task>\nimplement JWT auth\n</task>" in out


def test_structured_path_uses_xml_renderer():
    state = _empty_state()
    task = Task(
        title="Add JWT auth to /login",
        description="Implement HS256 JWT auth on /login.",
        kind="feature",
        acceptance_criteria=["POST /login returns a JWT on valid creds"],
    )
    out = build_iteration_prompt(
        "implement JWT auth",
        "expected: working endpoint",
        state,
        task=task,
    )
    assert "<title>Add JWT auth to /login</title>" in out
    assert "<acceptance-criteria>" in out
    # The legacy plain block must NOT also appear — single source of truth
    assert "<task>\nimplement JWT auth\n</task>" not in out


def test_synthesised_task_carries_auto_generated_marker():
    state = _empty_state()
    task = task_from_free_text(
        "Quiero agregar autenticación JWT al endpoint /login para issue #142."
    )
    out = build_iteration_prompt(
        task.description,
        "expected: working endpoint",
        state,
        task=task,
    )
    assert "<auto-generated" in out


def test_authored_task_omits_auto_generated_marker():
    state = _empty_state()
    task = Task(
        title="Add JWT auth",
        description="Implement HS256 JWT auth on /login.",
        kind="feature",
        acceptance_criteria=[
            "POST /login returns a JWT on valid creds",
            "Tokens expire after 24h",
        ],
    )
    out = build_iteration_prompt(
        task.description,
        "expected: working endpoint",
        state,
        task=task,
    )
    assert "<auto-generated" not in out
