"""Integration test: structured Task flows through to the iteration prompt.

Confirms that ``build_iteration_prompt`` renders the structured XML
block when a ``Task`` is passed and falls back to the legacy plain
``<task>desc</task>`` block when not. This is the contract the engine
relies on after the Task plumbing PR — both the principal and the
critic see whichever block is produced here.
"""

from __future__ import annotations

from infinidev.engine.loop.context import build_iteration_prompt
from infinidev.engine.loop.models import LoopState
from infinidev.engine.orchestration.task_schema import Task, task_from_free_text


def _empty_state() -> LoopState:
    return LoopState()


def test_legacy_path_uses_plain_task_block():
    state = _empty_state()
    out = build_iteration_prompt(
        "implement JWT auth",
        "expected: working endpoint",
        state,
    )
    assert "<task>\nimplement JWT auth\n</task>" in out


def test_structured_path_uses_xml_renderer():
    state = _empty_state()
    task = Task(
        title="Add JWT auth to /login",
        description="Implement HS256 JWT auth on /login.",
        kind="feature",
        acceptance_criteria=["POST /login returns a JWT on valid creds"],
    )
    out = build_iteration_prompt(
        "implement JWT auth",
        "expected: working endpoint",
        state,
        task=task,
    )
    assert "<title>Add JWT auth to /login</title>" in out
    assert "<acceptance-criteria>" in out
    # The legacy plain block must NOT also appear — single source of truth
    assert "<task>\nimplement JWT auth\n</task>" not in out


def test_synthesised_task_carries_auto_generated_marker():
    state = _empty_state()
    task = task_from_free_text(
        "Quiero agregar autenticación JWT al endpoint /login para issue #142."
    )
    out = build_iteration_prompt(
        task.description,
        "expected: working endpoint",
        state,
        task=task,
    )
    assert "<auto-generated" in out


def test_authored_task_omits_auto_generated_marker():
    state = _empty_state()
    task = Task(
        title="Add JWT auth",
        description="Implement HS256 JWT auth on /login.",
        kind="feature",
        acceptance_criteria=[
            "POST /login returns a JWT on valid creds",
            "Tokens expire after 24h",
        ],
    )
    out = build_iteration_prompt(
        task.description,
        "expected: working endpoint",
        state,
        task=task,
    )
    assert "<auto-generated" not in out


def test_structured_path_preserves_orchestration_context_without_duplicate_task():
    state = _empty_state()
    task = Task(
        title="Continue the GPU implementation",
        description="Continue the implementation from the grounded handoff.",
        kind="feature",
        acceptance_criteria=["The next grounded change is implemented and tested"],
    )
    description = """
<gathered-context>
The failing device test is named draw-indexed.
</gathered-context>

<task authority="USER_LITERAL">
This duplicate literal task block must be replaced by the structured Task.
</task>

<rolling-step-policy authority="SYSTEM">
Use the next evidence-backed Step.
</rolling-step-policy>

<retrieval-context source="ken" authority="advisory" scope-effect="none">
<context-rank>
Files:
- infinigpu/CONTINUE.md
- infinigpu/guest/icd/infinigpu_cmd_buffer.c
</context-rank>
</retrieval-context>
""".strip()

    out = build_iteration_prompt(
        description,
        "The requested implementation is complete.",
        state,
        task=task,
    )

    assert "<title>Continue the GPU implementation</title>" in out
    assert "duplicate literal task block" not in out
    assert "<gathered-context>" in out
    assert "<rolling-step-policy" in out
    assert "<retrieval-context source=\"ken\"" in out
    assert "infinigpu/CONTINUE.md" in out


def test_context_pressure_compacts_without_forcing_step_completion():
    state = _empty_state()
    state.last_prompt_tokens = 800_000

    out = build_iteration_prompt(
        "Implement the grounded GPU change",
        "Focused tests pass",
        state,
        max_context_tokens=1_000_000,
    )

    assert "Automatic context compaction is active" in out
    assert "Continue the Step normally" in out
    assert "not a completion signal" in out
    assert "wrap up NOW" not in out
    assert 'step_complete(status="done")' not in out
