"""Render :class:`Task` objects into the prompt as a structured XML block.

The renderer is the single source of truth for *how* the task appears
to LLMs. The principal sees this exact block at the top of every
iteration prompt; the critic sees the same block (forwarded via the
shared message history). Keeping rendering centralised guarantees
parity — if we ever drift apart between principal and critic, scope
detection silently breaks.

Empty optional sections are *omitted* rather than rendered as empty
tags, so a task with no out-of-scope items doesn't waste tokens on
``<out-of-scope></out-of-scope>``. Synthesised tasks (built from raw
free text via :func:`task_from_free_text`) get a leading
``<auto-generated note="..."/>`` marker so the critic knows the
acceptance criteria aren't user-authored.
"""

from __future__ import annotations

import html

from infinidev.engine.orchestration.task_schema import (
    SUGGESTED_TASK_KINDS,
    Task,
    is_synthesised,
)

_AUTO_NOTE = (
    'This task was auto-generated from raw user free-text. The '
    '<acceptance-criteria> below is a placeholder, not user-authored. '
    'Treat it with skepticism and ask the user for refinement if the '
    'work is non-trivial.'
)


def _escape(s: str) -> str:
    """XML-escape a string for safe inclusion in tag content.

    The prompt isn't parsed as real XML by the LLM, but we still escape
    to prevent unbalanced angle brackets in user content from breaking
    the visual structure (and to prevent prompt injection via embedded
    tags like ``</task>``).
    """
    return html.escape(s, quote=False)


def _render_list(tag: str, items: list[str], indent: str = "  ") -> str:
    """Render a list as ``<tag>``-bullet block. Returns empty string when no items."""
    if not items:
        return ""
    inner = "\n".join(f"{indent}- {_escape(item)}" for item in items)
    return f"<{tag}>\n{inner}\n</{tag}>"


def render_task_xml(task: Task) -> str:
    """Render a :class:`Task` as a ``<task>...</task>`` block.

    Sections in fixed order:

    1. Optional ``<auto-generated/>`` marker for synthesised tasks.
    2. ``<title>`` — one-liner.
    3. ``<kind>`` — with the official description if known.
    4. ``<description>`` — the user's full ask.
    5. ``<acceptance-criteria>`` — always present (≥1 by schema).
    6. ``<out-of-scope>`` — only if non-empty.
    7. ``<constraints>`` — only if non-empty.
    8. ``<references>`` — only if non-empty.
    """
    parts: list[str] = ["<task>"]

    if is_synthesised(task):
        parts.append(f'  <auto-generated note="{_escape(_AUTO_NOTE)}"/>')

    parts.append(f"  <title>{_escape(task.title)}</title>")

    kind_desc = SUGGESTED_TASK_KINDS.get(task.kind)
    if kind_desc:
        parts.append(
            f"  <kind name=\"{_escape(task.kind)}\">"
            f"{_escape(kind_desc)}</kind>"
        )
    else:
        parts.append(
            f"  <kind name=\"{_escape(task.kind)}\" "
            f"non-standard=\"true\"/>"
        )

    parts.append(f"  <description>\n{_escape(task.description)}\n  </description>")

    crit = _render_list("acceptance-criteria", task.acceptance_criteria, indent="    ")
    if crit:
        parts.append(f"  {crit}")

    oos = _render_list("out-of-scope", task.out_of_scope, indent="    ")
    if oos:
        parts.append(f"  {oos}")

    cons = _render_list("constraints", task.constraints, indent="    ")
    if cons:
        parts.append(f"  {cons}")

    refs = _render_list("references", task.references, indent="    ")
    if refs:
        parts.append(f"  {refs}")

    parts.append("</task>")
    return "\n".join(parts)
